### ISSUE TITLE
[관리자 페이지] `Header` 컴포넌트를 수정한다

### ISSUE THREAD

**Issue by Hmini0101** [woorifisa-projects/GoodFriends#116]
## 목적
관리자가 원하는 화면을 좀 더 보기 쉽게 왼쪽 사이드바를  클릭하면 열고 닫히는 기능을 추가한다.

## 상세 내용
- 사이드바 접고 펴는 기능을 하는 버튼로고 추가 및 기능 구현
- 로그아웃 기능 구현(임시)
- 전체화면 시각적으로 분할 및 개선(메뉴버튼로고,로그아웃 맨바깥페이지/ 사이드바 / 특정메뉴페이지)

## 참고 사항
> 참고할 내용 혹은 주소가 있다면 작성해 주세요.

## (예상)소요 시간
2시간

**Comment by devFancy** [comment]
해당 화면에 대한 스크린샷 혹은 동영상을 첨부해주시면 더 이해하기 쉬울 것 같아요~
